name: Checks on push.
on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Lint with flake8
      run: |
        pip install flake8 flake8-docstrings
        python -m flake8 . --count --show-source --statistics

    - name: Pytest
      run: |
        pip install pytest
        python -m pytest .